### ISSUE TITLE
Corresponding connectome for the neurons

### ISSUE THREAD

**Issue by lukablagoje** [HessMax/NeuronMorphologyQuantification#4]
Hi! 

I'm interested in using this data, but I cannot seem to find which neurons are synaptically connected (their connectome). 

Do you maybe have a file that tells which neurons in the dataset are connected to each other? If not, do you have any idea how to find this out? 

Best,
Luka

**Comment by MaksHess** [comment]
Hi Luka,

I can't tell you much about the connectivity of the neurons as that was not part of the project. Maybe this wiring-diagram from the wormbook helps (check paragraph 3):

http://www.wormbook.org/chapters/www_mechanosensation/mechanosensation.html

Best,
Max
